### PR TITLE
fix db memory data race

### PR DESCRIPTION
**Pull request by mffrench**
see ticket https://github.com/hyperledger-labs/fabric-smart-client/issues/276

Signed-off-by: Mathilde Ffrench <mathilde.ffrench@fr.ibm.com>

### CODE REVIEW

**Comment by adecaro** [comment]
@mffrench , please can you add a unit-test to check that the race condition is gone? Thanks :)

**Comment by mffrench** [comment]
@adecaro : would love to add such tests but need to rush on our app stack now :/ Currently only test for me to validate we don't get that datarace again is on our app stack...

Regarding tests validating no more datarace, we should handle all func available from db interface, run them in appropriate way in several go routine and test it against memory driver or other one and ...

**Comment by adecaro** [comment]
what I don't get is why there was a race condition before. Can you explain the rational of your changes, please?

**Review by adecaro — COMMENTED** [review]
LGTM for now, but need to be revised soon.

**Pull request merged**
